### ISSUE TITLE
feat: switch to opt-out metrics

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/ignite-metrics#2]
Note that until https://github.com/ipfs/ipfs-gui/issues/125, https://github.com/ipfs/ipfs-gui/issues/130, and https://discuss.ipfs.tech/t/ipfs-gui-metrics-changes-in-progress/15695 have been available to the community for feedback for enough time (at least two weeks: ETA Jan 20th), we will continue with the implementation we currently have in public-gateway-checker: 
* metrics implementation was already merged (https://github.com/ipfs/public-gateway-checker/pull/309), but it's not opt-out yet. I.e. until you accept/decline, no metrics are sent.

- [x] provide `necessary` consent on page-load
- [x] Allow users to disable `necessary` metrics (see https://github.com/ipfs/ipfs-gui/issues/125#issuecomment-1352295236)
    - [x] Send a metric when users disable necessary metrics. This would give us a signal about the number of users we have that prefer zero telemetry collection

**Comment by SgtPooki** [comment]
> Send a metric when users disable necessary metrics. This would give us a signal about the number of users we have that prefer zero telemetry collection

thoughts? @lidel @whizzzkid @tinytb

**Comment by lidel** [comment]
I am afraid this is still sending a telemetry: HTTP request will be reporting someone's IP and user-agent. 
Lying like that may be problematic from a legal standpoint: IP is considered private information in some jurisdictions.

Opt-out should be opt-out. When user opts-out,send  "opt-out" event once, and never send anything again.
You can infer what % of users opted-out from metrics by comparing the rolling averages (e.g. motnhly)  of first-install vs opt-out events or something :)

**Comment by SgtPooki** [comment]
> When user opts-out,send "opt-out" event once, and never send anything again.
This is exactly what I'm saying
