### ISSUE TITLE
analysis: Investigate which projects are react or not

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/ignite-metrics#32]
We need to determine whether to prioritize working on exports of react components from this library, or getting metrics integrated in all the projects listed at https://github.com/ipfs/ipfs-gui/issues/105. To do so, we need to know:

- How many of the projects listed in https://github.com/ipfs/ipfs-gui/issues/105 are using react
- Are the majority of those projects react? 
   - if not, don't prioritize react components
   - if so, prioritize react components styling and exports to match ipfs/public-gateway-checker/issues/341, ipfs/public-gateway-checker/issues/340, ipfs/public-gateway-checker/issues/342

The result of this task is to determine whether we will focus on exporting react components from this library prior to finishing #105, or doing this later.

**Comment by SgtPooki** [comment]
@djmcquillan any update?

**Comment by djmcquillan** [comment]
| Repo                                                        | React? |
|-------------------------------------------------------------|--------|
| https://github.com/ipfs/ipfs-desktop                        | - []   |
| https://github.com/ipfs/ipfs-webui                          | - [x]  |
| https://github.com/ipfs/ipfs-companion                      | - []   |
| https://github.com/ipfs/public-gateway-checker              | - []   |
| https://github.com/ipld/explore.ipld.io                     | - [x]  |
| https://github.com/ipfs-shipyard/pinning-service-compliance | - []   |
| https://github.com/ipfs-shipyard/ipfs-dag-builder-vis       | - [x]  |
| https://github.com/multiformats/cid-utils-website           | - []   |
| https://github.com/ipfs-shipyard/ipfs-share-files           | - [x]  |
| https://github.com/pln-planning-tools/Starmap               | - [x]  |
| https://github.com/ipfs-shipyard/ipfs-check                 | - []   |
| https://github.com/laurentsenta/pl-diagnose                 | - [x]  |

**Comment by SgtPooki** [comment]
I think we should focus on React components only. Of all projects other than desktop, webui, companion: 

- public-gateway-checker is being done by ipfs/public-gateway-checker#340
- there are 8 other projects, 5 of which are react.
